#!/bin/bash

# check parameters number
if [ "$#" -ne 1 ]; then
    echo "Error on parameters. Use: ./run <elf file>"
    exit
fi

# check file
if [ ! -f "$1" ]; then
	echo "File $1 not exists"
	exit
fi

FIFOLOGPATH="fifo.log"
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# create the Named Pipe
rm -f $FIFOLOGPATH
mkfifo $FIFOLOGPATH

# we start the terminal in another window executing kvm with the parameter passed to the script and set the log on the named pipe
xterm -fn "-misc-*-medium-*-*-*-*-*-100-*-*-70-*-*" -T "EndlessFault" -e "$SCRIPTPATH/kvm $1 -logfile $FIFOLOGPATH" &

#in the meanwhile we acquire kvm writes on the named pipe
cat < $FIFOLOGPATH
